### ISSUE TITLE
Spring解体新書（バッチ編）

### ISSUE THREAD

**Issue by Tatsukiyoshi** [Tatsukiyoshi/Weekend_Programming#16]
[書籍（Kindle版）](https://www.amazon.co.jp/gp/product/B09D3ZTJTB/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i1)のサンプルコードを元に、Kotlinで実践する

**Comment by Tatsukiyoshi** [comment]
ようやく、9.1.1を完了。
実行されないのは、アノテーション漏れ。漏れていてもコンパイルは通るけど、実行されません！
例外は、クエリへの配列の渡し方とマッパーのクラス指定かな。
モデルのメンバ属性は、JavaでprivateだったのをKotlinでopenにするのか？

**Comment by Tatsukiyoshi** [comment]
12章まで完了。残るは、13章（データベース）および14章（テスト）です。

**Comment by Tatsukiyoshi** [comment]
13章開始。13.1.1では、[MapJobExplorerFactoryBeanがサポート対象外](https://spring.pleiades.io/spring-batch/docs/current/api/org/springframework/batch/core/explore/support/MapJobExplorerFactoryBean.html)と実行時例外が課題。MapJobExplorerFactoryBeanについては、JobExplorerFactoryBeanが後継と判明し解消。
例外については、調査中。
```
C:\Users\taish\.jdks\corretto-17.0.4\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.2\lib\idea_rt.jar=51331:C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2022.1.2\bin" -Dfile.encoding=UTF-8 -classpath D:\Repository\Weekend_Programming\kotlin\spring\BatchInMemory\build\classes\kotlin\main;D:\Repository\Weekend_Programming\kotlin\spring\BatchInMemory\build\resources\main;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-batch\2.7.2\3e481c23f86316a64ff68d7b899b30c59ed60a46\spring-boot-starter-batch-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-data-jdbc\2.7.2\1c2f5738d8e54cd74980086c343559c5bc2f133d\spring-boot-starter-data-jdbc-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-data-jpa\2.7.2\11ac3a239c4644dc8e338fafff1fb66557abcf2f\spring-boot-starter-data-jpa-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-jdbc\2.7.2\d99e25fca0a37d6d88bd7561643284bc97555099\spring-boot-starter-jdbc-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.6.21\5dc3574d9b7bebfcb4ec6b10ada4aaa9e140bd0b\kotlin-reflect-1.6.21.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.6.21\eeb4d60d75e9ea9c11200d52974e522793b14fba\kotlin-stdlib-jdk8-1.6.21.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.projectlombok\lombok\1.18.22\9c08ea24c6eb714e2d6170e8122c069a0ba9aacf\lombok-1.18.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter\2.7.2\12f0da08b8120adcd137073ad08767f2d60e6cc3\spring-boot-starter-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.batch\spring-batch-core\4.3.6\86b8b16e53ccd167ac27bf46bea1ebce4a3dd484\spring-batch-core-4.3.6.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.data\spring-data-jdbc\2.4.2\e56e0532301a8a3e79b181904357dd1c61adb4af\spring-data-jdbc-2.4.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-aop\2.7.2\85ab2c70e97c11148f986ca4c901b678053cc39d\spring-boot-starter-aop-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\jakarta.transaction\jakarta.transaction-api\1.3.3\c4179d48720a1e87202115fbed6089bdc4195405\jakarta.transaction-api-1.3.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\jakarta.persistence\jakarta.persistence-api\2.2.3\8f6ea5daedc614f07a3654a455660145286f024e\jakarta.persistence-api-2.2.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.hibernate\hibernate-core\5.6.10.Final\408fd5802391d8e6f619db9d7c6c0e27d49118c2\hibernate-core-5.6.10.Final.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.data\spring-data-jpa\2.7.2\1b8783e98d4199c8fbcb46765fbfce02f41907fe\spring-data-jpa-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-aspects\5.3.22\1fdd8ac7f557ba12bb59086edfe3a9cdf6d918bf\spring-aspects-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.zaxxer\HikariCP\4.0.3\107cbdf0db6780a065f895ae9d8fbf3bb0e1c21f\HikariCP-4.0.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-jdbc\5.3.22\d50fc708ef9bade1d3fb64d529b8ff8cd5b625ba\spring-jdbc-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.6.21\11ef67f1900634fd951bad28c53ec957fabbe5b8\kotlin-stdlib-1.6.21.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.6.21\568c1b78a8e17a4f35b31f0a74e2916095ed74c2\kotlin-stdlib-jdk7-1.6.21.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-autoconfigure\2.7.2\f358e3f8ce01d3a26605fa23f9d3fd408726b033\spring-boot-autoconfigure-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot\2.7.2\a471deae9d806afa28ab888f75d46cff6e2f118c\spring-boot-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-starter-logging\2.7.2\a88c44d4ec24ca37f51192c2aad3a1ca53f937f5\spring-boot-starter-logging-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\jakarta.annotation\jakarta.annotation-api\1.3.5\59eb84ee0d616332ff44aba065f3888cf002cd2d\jakarta.annotation-api-1.3.5.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-core\5.3.22\661fc01832716c7eedebf995c6841b2f7117c63d\spring-core-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.yaml\snakeyaml\1.30\8fde7fe2586328ac3c68db92045e1c8759125000\snakeyaml-1.30.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.batch\spring-batch-infrastructure\4.3.6\2705e1ecee0fda29e2a94918e55919f55138c02\spring-batch-infrastructure-4.3.6.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-context\5.3.22\fdd59bb4795c7a399e95ec4a5c8b91103e3189fd\spring-context-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-aop\5.3.22\2f9f00efbff8432f145ccffeb93e6a1819bac362\spring-aop-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-tx\5.3.22\d0b3812ab20987a13f3a9ae7b4c54f619e034692\spring-tx-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-beans\5.3.22\866c2022b5fef05b1702f4a07cfa5598660ce08a\spring-beans-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-databind\2.13.3\56deb9ea2c93a7a556b3afbedd616d342963464e\jackson-databind-2.13.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\io.micrometer\micrometer-core\1.9.2\8eed85a5337c7b4e84156cc0f3921930fb0d780b\micrometer-core-1.9.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\javax.batch\javax.batch-api\1.0\65392d027a6eb369fd9fcd1b75cae150e25ac03c\javax.batch-api-1.0.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.codehaus.jettison\jettison\1.2\765a6181653f4b05c18c7a9e8f5c1f8269bf9b2\jettison-1.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.data\spring-data-relational\2.4.2\9b4069eecee943d12f1c23cfd23a861b8e1f5cb6\spring-data-relational-2.4.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.data\spring-data-commons\2.7.2\9547d1234cb380234066aef60129bb2ddfdc6347\spring-data-commons-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.slf4j\slf4j-api\1.7.36\6c62681a2f655b49963a5983b8b0950a6120ae14\slf4j-api-1.7.36.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.aspectj\aspectjweaver\1.9.7\158f5c255cd3e4408e795b79f7c3fbae9b53b7ca\aspectjweaver-1.9.7.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.hibernate.common\hibernate-commons-annotations\5.1.2.Final\e59ffdbc6ad09eeb33507b39ffcf287679a498c8\hibernate-commons-annotations-5.1.2.Final.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jboss.logging\jboss-logging\3.4.3.Final\c4bd7e12a745c0e7f6cf98c45cdcdf482fd827ea\jboss-logging-3.4.3.Final.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\net.bytebuddy\byte-buddy\1.12.12\8e864584dacba464c3abb6e2da8a2f0cbe1a7111\byte-buddy-1.12.12.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\antlr\antlr\2.7.7\83cd2cd674a217ade95a4bb83a8a14f351f48bd0\antlr-2.7.7.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jboss\jandex\2.4.2.Final\1e1c385990b258ff1a24c801e84aebbacf70eb39\jandex-2.4.2.Final.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.fasterxml\classmate\1.5.1\3fe0bed568c62df5e89f4f174c101eab25345b6c\classmate-1.5.1.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\jaxb-runtime\2.3.6\1e6cd0e5d9f9919c8c8824fb4d310b09a978a60e\jaxb-runtime-2.3.6.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-orm\5.3.22\abcefbf4895a3daf263cf385cc66e924db92d254\spring-orm-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.6.21\5e5b55c26dbc80372a920aef60eb774b714559b8\kotlin-stdlib-common-1.6.21.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-classic\1.2.11\4741689214e9d1e8408b206506cbe76d1c6a7d60\logback-classic-1.2.11.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-to-slf4j\2.17.2\17dd0fae2747d9a28c67bc9534108823d2376b46\log4j-to-slf4j-2.17.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.slf4j\jul-to-slf4j\1.7.36\ed46d81cef9c412a88caef405b58f93a678ff2ca\jul-to-slf4j-1.7.36.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-jcl\5.3.22\811ace5e5eb379654ed96fd7844809db51af74a5\spring-jcl-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.retry\spring-retry\1.3.3\13a6f4edb1f5a8956ec6aa867757e325bc98eee7\spring-retry-1.3.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework\spring-expression\5.3.22\c056f9e9994b18c95deead695f9471952d1f21d1\spring-expression-5.3.22.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-annotations\2.13.3\7198b3aac15285a49e218e08441c5f70af00fc51\jackson-annotations-2.13.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.fasterxml.jackson.core\jackson-core\2.13.3\a27014716e4421684416e5fa83d896ddb87002da\jackson-core-2.13.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.hdrhistogram\HdrHistogram\2.1.12\6eb7552156e0d517ae80cc2247be1427c8d90452\HdrHistogram-2.1.12.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\jakarta.xml.bind\jakarta.xml.bind-api\2.3.3\48e3b9cfc10752fba3521d6511f4165bea951801\jakarta.xml.bind-api-2.3.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.glassfish.jaxb\txw2\2.3.6\45db7b69a8f1ec2c21eb7d4fc0ee729f53c1addc\txw2-2.3.6.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.sun.istack\istack-commons-runtime\3.0.12\cbbe1a62b0cc6c85972e99d52aaee350153dc530\istack-commons-runtime-3.0.12.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\ch.qos.logback\logback-core\1.2.11\a01230df5ca5c34540cdaa3ad5efb012f1f1f792\logback-core-1.2.11.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.apache.logging.log4j\log4j-api\2.17.2\f42d6afa111b4dec5d2aea0fe2197240749a4ea6\log4j-api-2.17.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.springframework.boot\spring-boot-devtools\2.7.2\a59185396e6654c3fe0181bb4d4a083754c6214d\spring-boot-devtools-2.7.2.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.postgresql\postgresql\42.3.6\98e509e29657cd3633d93bc05ae41ff71fbb79d1\postgresql-42.3.6.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.checkerframework\checker-qual\3.5.0\2f50520c8abea66fbd8d26e481d3aef5c673b510\checker-qual-3.5.0.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\org.latencyutils\LatencyUtils\2.0.3\769c0b82cb2421c8256300e907298a9410a2a3d3\LatencyUtils-2.0.3.jar;C:\Users\taish\.gradle\caches\modules-2\files-2.1\com.sun.activation\jakarta.activation\1.2.2\74548703f9851017ce2f556066659438019e7eb5\jakarta.activation-1.2.2.jar com.example.demo.BatchInMemoryApplicationKt
06:49:05.253 [Thread-0] DEBUG org.springframework.boot.devtools.restart.classloader.RestartClassLoader - Created RestartClassLoader org.springframework.boot.devtools.restart.classloader.RestartClassLoader@7171ad96

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.2)

2022-07-26 06:49:06.104  INFO 15312 --- [  restartedMain] c.e.demo.BatchInMemoryApplicationKt      : Starting BatchInMemoryApplicationKt using Java 17.0.4 on IdeaPad550-2022 with PID 15312 (D:\Repository\Weekend_Programming\kotlin\spring\BatchInMemory\build\classes\kotlin\main started by taish in D:\Repository\Weekend_Programming\kotlin\spring\BatchInMemory)
2022-07-26 06:49:06.106  INFO 15312 --- [  restartedMain] c.e.demo.BatchInMemoryApplicationKt      : No active profile set, falling back to 1 default profile: "default"
2022-07-26 06:49:06.243  INFO 15312 --- [  restartedMain] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
2022-07-26 06:49:07.903  INFO 15312 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2022-07-26 06:49:07.903  INFO 15312 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JDBC repositories in DEFAULT mode.
2022-07-26 06:49:07.935  INFO 15312 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 8 ms. Found 0 JDBC repository interfaces.
2022-07-26 06:49:07.967  INFO 15312 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Multiple Spring Data modules found, entering strict repository configuration mode
2022-07-26 06:49:07.983  INFO 15312 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Bootstrapping Spring Data JPA repositories in DEFAULT mode.
2022-07-26 06:49:07.999  INFO 15312 --- [  restartedMain] .s.d.r.c.RepositoryConfigurationDelegate : Finished Spring Data repository scanning in 1 ms. Found 0 JPA repository interfaces.
2022-07-26 06:49:09.175  INFO 15312 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2022-07-26 06:49:09.744  INFO 15312 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2022-07-26 06:49:10.135  INFO 15312 --- [  restartedMain] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [name: default]
2022-07-26 06:49:10.617  INFO 15312 --- [  restartedMain] org.hibernate.Version                    : HHH000412: Hibernate ORM core version 5.6.10.Final
2022-07-26 06:49:10.903  INFO 15312 --- [  restartedMain] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
2022-07-26 06:49:11.103  INFO 15312 --- [  restartedMain] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL10Dialect
2022-07-26 06:49:11.528  INFO 15312 --- [  restartedMain] o.h.e.t.j.p.i.JtaPlatformInitiator       : HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
2022-07-26 06:49:11.544  INFO 15312 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Initialized JPA EntityManagerFactory for persistence unit 'default'
2022-07-26 06:49:11.716  WARN 15312 --- [  restartedMain] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customBatchConfigurer': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Initialization failure
2022-07-26 06:49:11.716  INFO 15312 --- [  restartedMain] j.LocalContainerEntityManagerFactoryBean : Closing JPA EntityManagerFactory for persistence unit 'default'
2022-07-26 06:49:11.716  INFO 15312 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-07-26 06:49:11.732  INFO 15312 --- [  restartedMain] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-07-26 06:49:11.748  INFO 15312 --- [  restartedMain] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-07-26 06:49:11.823 ERROR 15312 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'customBatchConfigurer': Invocation of init method failed; nested exception is java.lang.IllegalStateException: Initialization failure
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.2.jar:2.7.2]
	at com.example.demo.BatchInMemoryApplicationKt.main(BatchInMemoryApplication.kt:13) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.7.2.jar:2.7.2]
Caused by: java.lang.IllegalStateException: Initialization failure
	at com.example.demo.config.CustomBatchConfigurer.init(CustomBatchConfigurer.kt:43) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333) ~[spring-beans-5.3.22.jar:5.3.22]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157) ~[spring-beans-5.3.22.jar:5.3.22]
	... 22 common frames omitted
Caused by: java.lang.IllegalArgumentException: DataSource must not be null.
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.3.22.jar:5.3.22]
	at org.springframework.batch.core.repository.support.JobRepositoryFactoryBean.afterPropertiesSet(JobRepositoryFactoryBean.java:172) ~[spring-batch-core-4.3.6.jar:4.3.6]
	at com.example.demo.config.CustomBatchConfigurer.init(CustomBatchConfigurer.kt:29) ~[main/:na]
	... 29 common frames omitted


プロセスは終了コード 0 で終了しました
```

**Comment by Tatsukiyoshi** [comment]
いったん、廃要素のMapJobRepositoryFactoryBean, MapJobExplorerFactoryBeanで実行確認実施。
廃要素を使用しない実装を下記を参考に実装検証したい。
[ジョブの設定と実行＠Spring](https://spring.pleiades.io/spring-batch/docs/current/reference/html/job.html)

**Comment by Tatsukiyoshi** [comment]
14章にてテストコードを実装する中で、junitを使うにはテキストのMockitoがどうもフィットしない。調べてみると、kotlin用があるらしい。
下記を参照して、テストコードを見直したい。
[Using Mockito with Kotlin](https://springacademy.io/using-mockito-with-kotlin/)

**Comment by Tatsukiyoshi** [comment]
手探り状態から始めて、まずは、Kotlinでの書き直しにて、14章終了までこぎつけた。
引き続き、サンプルオリジナルのJavaで理解を深めることとする。
