### ISSUE TITLE
Webアプリ実装で学ぶ、現場で役立つRust入門

### ISSUE THREAD

**Issue by Tatsukiyoshi** [Tatsukiyoshi/Weekend_Programming#1601]
[Webアプリ実装で学ぶ、現場で役立つRust入門](https://atmarkit.itmedia.co.jp/ait/series/36943/) を学習する

**Comment by Tatsukiyoshi** [comment]
4/22 第2回まで完了

**Comment by Tatsukiyoshi** [comment]
4/22 第3回まで完了

**Comment by Tatsukiyoshi** [comment]
4/23 第4回まで完了

**Comment by Tatsukiyoshi** [comment]
4/23 第5回まで完了

**Comment by Tatsukiyoshi** [comment]
クッキー利用のパターンを追加しました。
残課題は解消されず。

**Comment by Tatsukiyoshi** [comment]
「投稿の登録および更新ではフラッシュメッセージが表示されない」課題修正
- `投稿表示ページのshowハンドラー関数も同様なので、配布サンプルを参照してください。`という説明を見落とし、サンプルを引用して修正することを忘れたための問題

**Comment by Tatsukiyoshi** [comment]
4/24 第６回まで完了

**Comment by Tatsukiyoshi** [comment]
4/24 第７回着手、未完了
- 構造体定義見直し中
- Dioxusクレート群は0.4.1限定
  最新0.5.1以降にあげるには変更点の確認が必要

**Comment by Tatsukiyoshi** [comment]
Dioxus 0.5.1に更新したものの、APIからの応答を表示できていないため、継続調査とする

**Comment by Tatsukiyoshi** [comment]
開発者ツールで確認したところ、CORSポリシーでブロックされているとのこと。
`origin 'http://localhost:8080' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
同じドメインでの共有を可能にする必要アリ。

**Comment by Tatsukiyoshi** [comment]
API側とAPI発行側の双方にCORS無効化処理追加
API側にはリクエストが届いており、警告メッセージも出ていないため、CORS無効化はできていると判断
しかし、実行時例外が発生し、応答を受信できない状況
```
Uncaught Error: url parse
    at imports.wbg.__wbindgen_throw (dioxus-posts.js:1514:15)
    at wasm_bindgen::throw_str::h98dd5fad0a7aa6aa (dioxus-posts_bg.wasm:0x4045b7)
    at <core::result::Result<T,E> as wasm_bindgen::UnwrapThrowExt<T>>::expect_throw::h8bf1f712d43f2da6 (dioxus-posts_bg.wasm:0x28ade0)
    at reqwest::wasm::client::fetch::{{closure}}::h52c37b8d8f401144 (dioxus-posts_bg.wasm:0x8f145)
    at reqwest::wasm::request::RequestBuilder::send::{{closure}}::hac8ab4d8e1c2241f (dioxus-posts_bg.wasm:0x1c3deb)
    at dioxus_posts5::data::call_index::{{closure}}::h41f15c75796fadc5 (dioxus-posts_bg.wasm:0x100066)
    at dioxus_posts5::app::{{closure}}::{{closure}}::h015a59997d1d4e2a (dioxus-posts_bg.wasm:0x1aa99f)
    at <core::pin::Pin<P> as core::future::future::Future>::poll::h74e93854bbd5d8cf (dioxus-posts_bg.wasm:0x3d09c3)
    at futures_util::future::future::FutureExt::poll_unpin::h34fb8f04c51ec5bb (dioxus-posts_bg.wasm:0x3e4e0e)
    at dioxus_hooks::use_resource::use_resource::{{closure}}::{{closure}}::{{closure}}::{{closure}}::hac33ce44fbd069af (dioxus-posts_bg.wasm:0x3f0e29)
```

**Comment by Tatsukiyoshi** [comment]
第８回（5/16公開）でDioxus 0.5.x対応の修正が反映された模様
うまくいっていなかった点が解消される見込み

**Comment by Tatsukiyoshi** [comment]
記事は公開されているものの、
コードがGithubに公開されていない。

**Comment by Tatsukiyoshi** [comment]
最新の第8回まで完了したので、いったんクローズする

**Comment by Tatsukiyoshi** [comment]
後続が公開されているので、再オープンする
また、バージョンも更新されるので、更新に合わせて実施する
- #1811

**Comment by Tatsukiyoshi** [comment]
連載続いてるので、15回まで取り組む。

**Comment by Tatsukiyoshi** [comment]
まず、写経済みコードを最新化し、FE部分を動作確認済
（※BE部分は、Actix-webでの実装）

**Comment by Tatsukiyoshi** [comment]
BE部分も最新化（Actix-web 4.9に更新）
ただし、FEでBEの結果を取得して表示できていない状況
```
Uncaught Error: url parse (C:\Users\taish\.cargo\registry\src\index.crates.io-6f17d22bba15001f\reqwest-0.12.11\src\wasm\client.rs:241:42): RelativeUrlWithoutBase
    at imports.wbg.__wbindgen_throw (dioxus-posts.js:1741:15)
    at dioxus_posts-48bfe8004a59bd0f.wasm.wasm_bindgen::throw_str::h4aafb593679f9ced (dioxus-posts_bg.wasm:0x11d7d7)
    at dioxus_posts-48bfe8004a59bd0f.wasm.<core::result::Result<T,E> as wasm_bindgen::UnwrapThrowExt<T>>::expect_throw::hcf7e8675882a4d4e (dioxus-posts_bg.wasm:0xeed2a)
    at dioxus_posts-48bfe8004a59bd0f.wasm.futures_util::future::future::FutureExt::poll_unpin::h24a15f244f1ea1a5 (dioxus-posts_bg.wasm:0x10342)
    at dioxus_posts-48bfe8004a59bd0f.wasm.dioxus_core::reactive_context::ReactiveContext::run_in::h336a852549d49ffd (dioxus-posts_bg.wasm:0xa050e)
    at dioxus_posts-48bfe8004a59bd0f.wasm.dioxus_hooks::use_resource::use_resource::{{closure}}::{{closure}}::hf1716525d7dd01bb (dioxus-posts_bg.wasm:0xd3013)
    at dioxus_posts-48bfe8004a59bd0f.wasm.dioxus_core::runtime::Runtime::with_scope_on_stack::h29a856b4a37046e1 (dioxus-posts_bg.wasm:0xb4b72)
    at dioxus_posts-48bfe8004a59bd0f.wasm.dioxus_core::tasks::<impl dioxus_core::runtime::Runtime>::handle_task_wakeup::hde3f5be22bc882ea (dioxus-posts_bg.wasm:0xc2240)
    at dioxus_posts-48bfe8004a59bd0f.wasm.dioxus_core::virtual_dom::VirtualDom::poll_tasks::h976830e177bdb67e (dioxus-posts_bg.wasm:0x338d4)
    at dioxus_posts-48bfe8004a59bd0f.wasm.dioxus_core::virtual_dom::VirtualDom::process_events::h6dc04eb578395528 (dioxus-posts_bg.wasm:0x5ed3e)
```
